### ISSUE TITLE
Making use of CSS inheritance

### ISSUE THREAD

**Issue by reviewer99** [ijbenton/prj-rev-bwfs-dasmoto#3]
When writing your CSS styles it is best to try and eliminate any duplicate styles found in your stylesheet as it makes it easier to make changes in the future.

For example here instead of the following:
```CSS
 #brushes h2 { 
   font-family: Helvetica; 
   font-size: 32px; 
   font-weight: bold; 
   color: white; 
   background-color: mediumspringgreen; 
 } 
 #frames h2 { 
   font-family: Helvetica; 
   font-size: 32px; 
   font-weight: bold; 
   color: white; 
   background-color: lightcoral; 
 } 
 #paint h2 { 
   font-family: Helvetica; 
   font-size: 32px; 
   font-weight: bold; 
   color: white; 
   background-color: skyblue; 
 } 
```

You could have done something like this:
```CSS
h2 {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}

#brushes h2 {
  background-color: mediumspringgreen;
}

#frames h2 {
  background-color: lightcoral;
}

#paint h2 {
  background-color: skyblue;
}
```

This way all your `h2`s inherit the styles they all share and you only need to apply the unique background they all have.

https://github.com/ijbenton/prj-rev-bwfs-dasmoto/blob/20131ffb7abaf1f379abd803b7fedd3350892e4d/Dasmoto's%20Arts%20%26%20Crafts/resources/css/index.css#L9-L29
